# Config file for Air live reload
root = "."

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  log = "stdout"
  poll = false
  delay = 1000 # ms

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[run]
  cmd = ""
  args = []
  env = ["GIN_MODE=debug"]
  env_file = ".env"
